# Generated by Django 3.0 on 2019-12-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    inital = True

    dependencies =[
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('gram', models.IntegerField(default = 0)),
                ('calories',models.IntegerField(default = 0)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
        